[package]
name = "denvl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.0", features = ["cargo"] }
daemonize = "0.4.0"
jsonrpc = "0.14.0"
nix = "0.26.0"
rand = "0.8.5"